text="
-- Create databases
CREATE DATABASE IF NOT EXISTS ${DB_ORCHESTRATOR_NAME};

CREATE DATABASE IF NOT EXISTS ${DB_WORKFLOW_NAME};

-- Create users and grant rights
CREATE USER '${DB_ORCHESTRATOR_USERNAME}'@'%' IDENTIFIED BY '${DB_ORCHESTRATOR_PASSWORD}';

CREATE USER '${DB_WORKFLOW_USERNAME}'@'%' IDENTIFIED BY '${DB_WORKFLOW_PASSWORD}';

GRANT ALL PRIVILEGES ON ${DB_ORCHESTRATOR_NAME}.* TO '${DB_ORCHESTRATOR_USERNAME}'@'%';
-- GRANT XA_RECOVER_ADMIN ON *.* TO '${DB_ORCHESTRATOR_USERNAME}'@'%';

GRANT ALL PRIVILEGES ON ${DB_WORKFLOW_NAME}.* TO '${DB_WORKFLOW_USERNAME}'@'%';
-- GRANT XA_RECOVER_ADMIN ON *.* TO '${DB_WORKFLOW_USERNAME}'@'%';
"

mysql --user="root" --password="${MYSQL_ROOT_PASSWORD}" --execute="${text}"
